[programs.localnet]
deep_waifu_payment_contract = "deepDCigiqV6vbvjbXQRvYsQGcWc7ynVgVo3qBAj2DJ"

[programs.devnet]
deep_waifu_payment_contract = "deepDCigiqV6vbvjbXQRvYsQGcWc7ynVgVo3qBAj2DJ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/marcin/.config/solana/id.json"

[provider.devnet]
cluster = "devnet"
wallet = "/home/marcin/.config/solana/devnet.json"

[scripts]
test = "mocha -t 1000000 tests/"
