[programs.localnet]
deep_waifu_payment_contract = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/marcin/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
